import string


VALID_SYMBOLS_SET = string.ascii_letters + string.digits
DEFAULT_LINK_LENGTH = 6
CUSTOM_LINK_LENGTH = 16
MAX_ORIGINAL_LINK_LENGTH = 200_000
GENERATED_RANDOM_STRING_TRY_COUNT = 1000

REGEXP_ID = fr'^[{VALID_SYMBOLS_SET}]+$'
